let g:markdown_github_flavored = 1

let g:_rtp_here = expand("<sfile>:h:h")
let &runtimepath = g:_rtp_here . "," . &runtimepath

set nocompatible
syntax on
filetype plugin  on

set noswapfile
set list
set listchars=tab:].,trail:\|,extends:<,precedes:>
set number
